/*
========================

Copyright (c) 2014 Vinyl Games Studio

	NetworkMessageIDs.h

		Created by: Vladyslav Dolhopolov
		Created on: 5/22/2014 1:57:27 PM

========================
*/
#ifndef __NETWORKMESSAGEIDS_H__
#define __NETWORKMESSAGEIDS_H__

#include <MessageIdentifiers.h>

enum class ToneArmMessage : unsigned char
{
	ID_ENGINE_SHUTDOWN = DefaultMessageIDTypes::ID_USER_PACKET_ENUM + 1,
	
	ID_ENGINE_JOIN_REQUEST,
	ID_ENGINE_JOIN_REQUEST_ACCEPTED,
	ID_ENGINE_JOIN_REQUEST_REJECTED,

	ID_ENGINE_FORCE_DISCONNECT_REQUEST,

	ID_ENGINE_CLIENT_DISCONNECTED,
	
	ID_ENGINE_LAST_PACKET_ENUM
};

// TODO: move to a separate file
enum class MerryMessage : unsigned char
{
	ID_MERRY_FIRST_PACKET_ENUM = ToneArmMessage::ID_ENGINE_LAST_PACKET_ENUM,

	ID_MERRY_INPUT,

	ID_MERRY_PREGAME_SETUP_REQUEST,
	ID_MERRY_PREGAME_SETUP_ANSWER,
	ID_MERRY_PREGAME_UPDATE,
	ID_MERRY_PREGAME_UPDATE_PROCESSED,

	ID_MERRY_INGAME_UPDATE,
	ID_MERRY_INGAME_HIT,
	ID_MERRY_INGAME_KILLED,
	ID_MERRY_INGAME_RESPAWNED,
	ID_MERRY_INGAME_CHANGE_WEAPON,
	ID_MERRY_INGAME_RELOAD,
	ID_MERRY_INGAME_BASIC_STATS_CHANGED,
	ID_MERRY_INGAME_BUFF_APPLIED,
	ID_MERRY_INGAME_OBJECT_PICKED,

	ID_MERRY_POSTGAME_ROUND_FINISHED,
	ID_MERRY_POSTGAME_ROUND_RESTARTED,

	ID_MERRY_NEW_PLAYER_CONNECTED,
	ID_MERRY_PLAYER_DISCONNECTED,

	ID_MERRY_LAST_PACKET_ENUM
};

enum class RejectReason : unsigned char
{
	ID_REJECT_SERVER_FULL,
};

#endif __NETWORKMESSAGEIDS_H__